server:
  port: 9090
spring:
  application:
    name: "Request"
  devtools:
    add-properties: false
  sql:
    init:
      mode: always
  profiles:
    include: null

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:9090"

routes:
  paths:
    state:
      create: "/api/v1/state"
    typeloan:
      create: "/api/v1/typeloan"
    loan-application:
      create: "/api/v1/loan-application"
      paginated: "/api/v1/loan-application/paginated"
      change-status: "/api/v1/loan-application/{id}"

#logging:
#  level:
#    org.springframework.r2dbc.core: DEBUG
#    io.r2dbc.postgresql: DEBUG


adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: ${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /api/docs
  version: 1.0.0
  title: Request Service
  description: API documentation for the Request Service
  license:
    name: GNU GENERAL PUBLIC LICENSE
    url: https://www.gnu.org/licenses/gpl-3.0.txt

services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

aws:
  sqs:
    region: ${SQS_REGION}
    accessKey: ${SQS_ACCESS_KEY}
    secretKey: ${SQS_SECRET_KEY}
    queueName: ${SQS_LOAN_APPLICATION_STATUS_QUEUE_NAME}